name: $(Date:yyyyMMdd)$(Rev:rr)
resources:
- repo: self

trigger:
  batch: 'true'
  branches:
    include:
    - master

pool:
  vmImage: 'VS2017-Win2016'

steps:
  - task: SonarCloudPrepare@1
    inputs:
      SonarCloud: 'SonarCloud'
      organization: 'cmdty'
      scannerMode: 'MSBuild'
      projectKey: 'storage'
      projectName: 'storage'

  - task: PowerShell@2
    displayName: 'Run Cake PowerShell Bootstrapper'
    inputs:
      filePath: 'build.ps1'
      arguments: '-Verbosity Diagnostic -Target CI -BuildNumber=$(Build.BuildNumber)'
    env:
      SYSTEM_ACCESSTOKEN: $(System.AccessToken)

  - task: SonarCloudAnalyze@1

  - task: PublishTestResults@2
    displayName: Publish Python test results
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: 'junit/test-results.xml'
      mergeTestResults: true
      testRunTitle: 'Python Unit Tests'

  - task: PublishTestResults@2
    displayName: 'Publish .NET test results'
    condition: succeededOrFailed()
    inputs:
      testResultsFormat: 'VSTest'
      testResultsFiles: '**/*.trx'
      mergeTestResults: true
      testRunTitle: 'C# Unit Tests'

  - task: PublishCodeCoverageResults@1
    displayName: 'publish .NET coverage results'
    condition: succeededOrFailed()
    inputs:
      codeCoverageTool: 'cobertura'
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.cobertura.xml'

  - task: TwineAuthenticate@0
    inputs:
      artifactFeeds: 'cmdty'
    displayName: 'Twine Authenticate'

  - script: 'twine upload -r cmdty --config-file $(PYPIRC_PATH) src/Cmdty.Storage.Python/dist/**'
    displayName: 'Upload Python package to Azure Artifacts Cmdty Feed'

  - task: CopyFiles@2
    displayName: Copy Python package to Artifact Staging Directory
    inputs:
      Contents: src/Cmdty.Storage.Python/dist/**
      TargetFolder: $(Build.ArtifactStagingDirectory)
      cleanTargetFolder: true
      flattenFolders: true

  - task: CopyFiles@2
    displayName: Copy NuGet package to Artifact Staging Directory
    inputs:
      Contents: artifacts/**
      TargetFolder: $(Build.ArtifactStagingDirectory)
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: 'publish artifacts'
    inputs:
      ArtifactName: 'drop'
